### ISSUE TITLE
Use integrated terminal profile 

### ISSUE THREAD

**Issue by maksim-pinguin** [eclipse-theia/vscode-builtin-extensions#100]
Hi,
I configured cygwin for my integrated Terminal in VSCode. 
like this: 
```
  "terminal.integrated.profiles.windows": {
        "Cygwin": {
          "path": "C:\\cygwin\\bin\\bash.exe",
          "args": ["--login"],
          "env": {"CHERE_INVOKING": "1"}
        }
    }
```
now gitlense repects this setting but this build in unfortunatly not.

**Comment by vince-fugnitto** [comment]
@maksim-pinguin thank you for reporting the issue, I'm not sure I understand the problem however? Which application are you currently using the builtin with? As far as I can tell `terminal.integrated.profiles.windows` does not come from a builtin but comes from vscode's sources itself:

- https://github.com/microsoft/vscode/blob/main/src/vs/platform/terminal/common/terminalPlatformConfiguration.ts#L248-L311

**Comment by maksim-pinguin** [comment]
Hi @vince-fugnitto,
 Thx for the quick reply.

Sorry for the misunderstanding. I meant the built in git extension of vscode is not using the integrated terminal as it should.


I'm using cygwin as my integrated terminal get a bash on windows. Now gitlense seems to respect those settings (so uses cygwin/bash) but vscodes git built-in doesn't (it uses windows CMd/ps). So it's necessary to set different paths. 

Gitlens.advanced.git would be a good option here, unfortunately it was removed . Now there's a conflict git built in expects gitpath to a windows git binary and gitlense (with the integrated terminal configured) needs the cygwin/unix version.

**Comment by vince-fugnitto** [comment]
> Sorry for the misunderstanding. I meant the built in git extension of vscode is not using the integrated terminal as it should.

@maksim-pinguin is it an issue you experience in vscode itself as well?

**Comment by maksim-pinguin** [comment]
Yes

**Comment by vince-fugnitto** [comment]
> Yes

@maksim-pinguin I think the issue should be opened in vscode itself then, this repo doesn’t update vscode’s sources, only packages their `extensions` folder so we can consume their builtin extensions in products that support the VS Code API. If there is a bug in the actual extension then the fix would be in VS Code’s sources itself.

**Comment by maksim-pinguin** [comment]
I already opened an issue on vscode, but it's been closed due to being out of scope. I don't understand why it's out of scope to just use the environment of the integrated terminal. 

Can you maybe explain me how I could the gitlens.advanced.git configuration back?

**Comment by vince-fugnitto** [comment]
@maksim-pinguin as I mentioned previously (https://github.com/eclipse-theia/vscode-builtin-extensions/issues/100#issuecomment-1117726190), this repository does not actually contain any of the sources of the builtins provided by vscode (ex: [git-base](https://github.com/microsoft/vscode/tree/main/extensions/git-base)), it only builds and packages the [`extensions`](https://github.com/microsoft/vscode/tree/main/extensions) folder into `.vsix` so they can be consumed/used by other products. If you need to modify actual code, it would be done in vscode's sources, possibly by forking their repository. It is very much out of scope of this simple repo.
