### ISSUE TITLE
Add settings to configure default URL

### ISSUE THREAD

**Issue by archiewood** [eclipse-theia/vscode-builtin-extensions#107]
I use simple browser quite a lot while developing front end stuff, in a split window with the code I'm editing:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/58074498/211073520-4962ef7d-7688-412c-b308-2548b58a9267.png">

Every time I boot simple browser up when developing, it asks me for the URL:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/58074498/211072473-6e7fa40a-1df2-4997-a4f7-3d78126919e3.png">

I get mildly bored with typing in `http://localhost:3000` every time.

Would be nice if it had setting to allow either:
- Instantly navigates to a default "homepage" which user could configure
- Autofills the above bar with your chosen URL, which you could edit

Or alike

I'd use this a bunch, and could perhaps try to contribute it if maintainers are open to it (but haven't worked on VSCode extensions before!)

**Comment by CiciDongxue** [comment]
您好，我已收到您的来信，暂时无法回复您的邮件，望见谅。

**Comment by msujew** [comment]
Hey @archiewood,

this is the [Eclipse Theia](https://theia-ide.org/) repo which hosts our custom build for vscode extensions. We just consume the extensions that Microsoft provide in their upstream repo, build them and upload them to [open-vsx](https://open-vsx.org/). If you have any feedback for the vscode team, you'd be served best by asking them in their repo [microsoft/vscode](https://github.com/microsoft/vscode).
