### ISSUE TITLE
Re-license this repo to match Eclipse Theia, contribute it to project

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/vscode-builtin-extensions#16]
We should have an open-source license. I can add it if we agree on which one. Apache 2? EPL 2?

**Comment by akosyakov** [comment]
VS Code extensions are distributed under MIT? Are we allowed to change it?

**Comment by marcdumais-work** [comment]
I think the VS Code git submodule and the extensions we build from it retain their original MIT license, unless we care to re-license them (permitted by MIT license). I would just leave that part as-is.

But we need a license that will cover everything else. Thinking of it, we'll publish the extensions from GH if we can get that to work, so it might be confusing to have two different licenses - one for the infrastructure and one for the extensions we publish. Maybe we can use MIT as well for the original content of this repo? 

the

**Comment by akosyakov** [comment]
> Maybe we can use MIT as well for the original content of this repo?

I would be fine with that.

**Comment by marcdumais-work** [comment]
> I don't think we are going to move this project under eclipse, or do we?

Good question - I am not sure.  It's possible that the Foundation may eventually prefer that this be part of our official Foundation-hosted project. Adopting an Eclipse Foundation friendly license would make the eventual move much easier. 

So to keep our options open, I would suggest we either go with the same license as the main project (EPL v2 or GPL v2 with GNU classpath exception) so there is no need to re-license, or MIT which permits easy re-licensing.

cc: @benoitf @tsmaeder

**Comment by marcdumais-work** [comment]
This repo is being considered for re-licensing to the Eclipse Theia license and "contributed" to it. Stay tuned.

see also: 
- https://github.com/theia-ide/theia-website/issues/122
- https://github.com/theia-ide/generator-theia-extension/issues/60

**Comment by marcdumais-work** [comment]
I created a wiki to track progress of re-licensing: https://github.com/theia-ide/vscode-builtin-extensions/wiki/Re-licensing-theia-ide-vscode-builtin-extensions

**Comment by marcdumais-work** [comment]
All permissions have been received for this repo, so the re-licensing exercise is a success. The next commit should be to add the new license to the repo. Making the repo up-to the Eclipse Foundation in other respects can be done later.

**Comment by marcdumais-work** [comment]
The License has been added and the repo moved to `eclipse-theia` GH org. There may be little things to fix after, but for now this is done.
