### ISSUE TITLE
Make built-ins extension pack

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/vscode-builtin-extensions#25]
As a follow-up to https://github.com/theia-ide/vscode-builtin-extensions/pull/20, I was thinking that it would probably be easy to make an extension pack that would contain the subset of built-ins that are know to work well. 

It would be useful as a shortcut to install the built-ins in one step

**Comment by akosyakov** [comment]
But for example apps we should not use pack but concrete extensions that extenders could pick.

**Comment by marcdumais-work** [comment]
@akosyakov I am ok with that - the example applications can be a showcase of individual extensions that one can pick, in a granular way. 

Are you ok with the applications in `theia-apps` using an extension pack to pull all the working built-ins instead of individual links?

**Comment by akosyakov** [comment]
yes for theia-apps is fine

I wonder since we published to Open VSX Registry already, it would be good to make a PR in theia repo to update links

**Comment by marcdumais-work** [comment]
@vince-fugnitto Would you have time to update the built-ins used in the main repo's example applications, to use the public Open VSX registry instead of GH Releases? 

e.g. a random one:
registry page: http://open-vsx.org/extension/vscode/vb
Download link: http://open-vsx.org/api/vscode/vb/file/vscode.vb-1.39.1.vsix

**Comment by marcdumais-work** [comment]
Closing in favor of: https://github.com/eclipse-theia/vscode-builtin-extensions/issues/40
