### ISSUE TITLE
Intellisense not available for launch.json

### ISSUE THREAD

**Issue by Johannes-B-stock** [eclipse-theia/vscode-builtin-extensions#37]
The json-language-features extension is not working anymore and throws the following exception: 

root ERROR [hosted-plugin: 20200] Promise rejection not handled in one second: TypeError: i.charAt is not a function , reason: TypeError: i.charAt is not a function
root ERROR [hosted-plugin: 20200] With stack trace: TypeError: i.charAt is not a function
    at c:\Users\...\AppData\Local\Temp\vscode-unpacked\json-language-features-1.39.1-prel.vsix\extension\client\dist\jsonMain.js:1:114840
    at Array.forEach (<anonymous>)
    at c:\Users\...\AppData\Local\Temp\vscode-unpacked\json-language-features-1.39.1-prel.vsix\extension\client\dist\jsonMain.js:1:114554
    at Array.forEach (<anonymous>)
    at v (c:\Users\...\AppData\Local\Temp\vscode-unpacked\json-language-features-1.39.1-prel.vsix\extension\client\dist\jsonMain.js:1:114416)
    at c:\Users\...\AppData\Local\Temp\vscode-unpacked\json-language-features-1.39.1-prel.vsix\extension\client\dist\jsonMain.js:1:119115
    at runNextTicks (internal/process/task_queues.js:59:5)
    at processImmediate (internal/timers.js:412:9)

**Comment by vince-fugnitto** [comment]
@Johannes-B-stock the `json-language-features` builtin extension works quite well, we use a much [newer version](https://github.com/eclipse-theia/theia/blob/deccec686f295f2b758133048f5a1a3479ca4e8a/package.json#L112) as part of the framework examples: 

```json
    "vscode-builtin-json-language-features": "https://open-vsx.org/api/vscode/json-language-features/1.46.1/file/vscode.json-language-features-1.46.1.vsix",
```

![launch](https://user-images.githubusercontent.com/40359487/97300949-80e4b800-182d-11eb-8032-84e220c409f1.gif)

**Comment by marcdumais-work** [comment]
As per the comment above, please try a later version  of that extension, perhaps v1.46.1
