### ISSUE TITLE
Re-publish v1.44.2

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/vscode-builtin-extensions#41]
upstream issue: https://github.com/eclipse-theia/theia/issues/9014

This repo's CI is configured to publish with the `open-vsx` bot's credentials. I think we can  tweak it to publish an arbitrary version, so long as `open-vsx.org` lets it happen.

**Comment by marcdumais-work** [comment]
Almost working - I think all that's needed now is for the originally published builtins v1.44.2 to be removed from the registry and to restart this [GH workflow](https://github.com/theia-ide/vscode-builtin-extensions/actions/runs/529364718)

[Current error](https://github.com/theia-ide/vscode-builtin-extensions/runs/1811159824?check_suite_focus=true#step:9:11):
_failed to publish bat-1.44.2.vsix: Error: Extension vscode.bat version 1.44.2 is already published, but is currently inactive and therefore not visible_

**Comment by marcdumais-work** [comment]
@spoenemann I think we can use the new GH action I recently added to re-publish 1.44.2, if someone can delete these vscode-builtins from open-vsx.org.

**Comment by spoenemann** [comment]
Deleted :+1:

**Comment by marcdumais-work** [comment]
I am attempting to re-publish markdown-language-features v1.39.2: https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824045224?check_suite_focus=true

If that works, I'll try with the full set of builtins v1.44.2 next

**Comment by marcdumais-work** [comment]
> I am attempting to re-publish markdown-language-features v1.39.2: https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824045224?check_suite_focus=true

another try: https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824119038?check_suite_focus=true

**Comment by marcdumais-work** [comment]
Success: https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824119038?check_suite_focus=true#step:10:11
https://open-vsx.org/extension/vscode/markdown-language-features/1.39.2

**Comment by marcdumais-work** [comment]
Now trying for the set of vscode-builtins v1.44.2:
https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824273641?check_suite_focus=true

**Comment by marcdumais-work** [comment]
> Now trying for the set of vscode-builtins v1.44.2:

@spoenemann Is it possible you missed removing [one extension](https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1824273641?check_suite_focus=true#step:9:148)?, `typescript-language-features-1.44.2.vsix` : 

```
publishing:  /home/runner/work/vscode-builtin-extensions/vscode-builtin-extensions/dist/typescript-language-features-1.44.2.vsix  
failed to publish typescript-language-features-1.44.2.vsix: Error: Extension vscode.typescript-language-features version 1.44.2 is already published, but is currently inactive and therefore not visible.
Stopping here. Fix the problem and retry.
```

**Comment by marcdumais-work** [comment]
Before encountering the error above, a good number of `v1.44.2` builtins were published. We'll need to re-run the workflow to finish once the extension above is removed.

**Comment by marcdumais-work** [comment]
I changed the publish script slightly to permit continuying when an extension fails to publish. All but `typescript-language-features-1.44.2.vsix` published fine. We can re-run the workflow to re-try with that one, once deleted from the registry.

**Comment by spoenemann** [comment]
It seems that one slipped through. It's deleted now.

**Comment by marcdumais-work** [comment]
I re-ran the workflow and `typescript-language-features-1.44.2.vsix` is [now published](https://open-vsx.org/extension/vscode/typescript/1.44.2), completing the `1.44.2` set:
https://github.com/eclipse-theia/vscode-builtin-extensions/runs/1857557848?check_suite_focus=true#step:9:13
