### ISSUE TITLE
Remove npm-publish (publish-next) workflow

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/vscode-builtin-extensions#51]
We have not updated the `vscode` git sub-repo is a while, so that workflow still builds/publishes the same old version of the builtins. The last update was about a year ago. I think everyone has probably switched to `open-vsx.org` and we can remove [this workflow](https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/.github/workflows/publish-next.yml). 

see: https://github.com/eclipse-theia/vscode-builtin-extensions/pull/50#issuecomment-792926374

**Comment by marcdumais-work** [comment]
cc: @akosyakov : Any objections?

**Comment by marcdumais-work** [comment]
Technically we  still publish to `npm`, but that workflow I think relies on the version of vscode git submodule, that checked-in the repo. That has not chaged in a long time, so we re-publish `v1.44.2`. We could go ahead and remove the workflow, altogether.

**Comment by vince-fugnitto** [comment]
Closed thanks to #83
