### ISSUE TITLE
Update build to use node 12

### ISSUE THREAD

**Issue by ericwill** [eclipse-theia/vscode-builtin-extensions#57]
Currently, the built-ins from this repo are built using node 10. Node 12 is the version used by VS Code to compile its extensions, thus it should be using that one.

We (Che) often need to build these built-ins from source, so having an up to date build process is ideal.

Che issue: https://github.com/eclipse/che/issues/19342
cc @tsmaeder

**Comment by tsmaeder** [comment]
Actually, VS Code is fine with anythything from 10.x to14.x: https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by benoitf** [comment]
all package.json and yarn.lock reference "@types/node" `^12.19.9`
so using nodejs 10 may not satisfy the requirement.

and electron 11 is using nodejs12

**Comment by marcdumais-work** [comment]
Sounds like it would be good to upgrade. One thing to note: if we ever need to build older version of the build-ins, we'll need to roll-back the node version. It's probably already true that we can go back only so far without having to use node 8.
