### ISSUE TITLE
Confusion about builtin plugins versions

### ISSUE THREAD

**Issue by xeor** [eclipse-theia/vscode-builtin-extensions#61]
In https://github.com/theia-ide/theia-apps/blob/master/theia-electron/package.json and all other places, the version in use is `v1.39.1-prel`. I see that ms is not releasing these plugins, but why aren't their up-to-date'ness getting more love?

https://github.com/eclipse-theia/vscode-builtin-extensions/issues/5#issuecomment-631285109 mentions that the `Open VSX Registry` should be used now, but I also find https://www.npmjs.com/package/@theia/vscode-builtin-docker (and many others), that are on version `0.2.1`, but seams like recently updated.

This all raises some questions and confusion:
* Are the plugins on `v1.39.1-prel` so static that this old version is "fine"?
* Should we really be using something else? The npm versions?
* Is the package.json files on https://github.com/theia-ide/theia-apps updated
* Is there a work-in-progress issue to make the situation better that I haven't discovered?

**Comment by vince-fugnitto** [comment]
@xeor builtins are published to `open-vsx` and not `npm`, for example:
- https://open-vsx.org/extension/vscode/typescript

You will see a list of all versions which can be downloaded in the dropdown.

**Comment by xeor** [comment]
Thanks @vince-fugnitto .. So instead of

`"vscode-builtin-docker": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/docker-1.39.1-prel.vsix",` in the package.json, it should now really be:

`"vscode-builtin-docker": "https://open-vsx.org/api/vscode/docker/1.55.2/file/vscode.docker-1.55.2.vsix",`, and kept updated.. Makes more sense, but I'm not sure why this is better documented? work-in-progress? Not ready for primetime?

**Comment by vince-fugnitto** [comment]
> Makes more sense, but I'm not sure why this is better documented? work-in-progress? Not ready for primetime?

@xeor application developers are free to choose whichever builtins they want, and are able to consume them from any URL. The `vscode-builtin-*` extensions are published to `open-vsx`. If you'd like to bundle them with your application  you can include them in your `package.json`, else users are able to install them from the extensions-view (part of the application).

- https://github.com/eclipse-theia/vscode-builtin-extensions#publishing-vscode-builtin-extensions-to-open-vsx
- https://github.com/eclipse-theia/vscode-builtin-extensions#re-publishing-vscode-builtin-extensions-to-open-vsx

**Comment by marcdumais-work** [comment]
@vince-fugnitto part of the confusion is that we still publish on npm: https://github.com/eclipse-theia/vscode-builtin-extensions/issues/51, though always the same version, so it does not look like we do.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto part of the confusion is that we still publish on npm: #51, though always the same version, so it does not look like we do.

@marcdumais-work I think we can remove that workflow like you've mentioned, we do not consume builtins as part as npm packages as far as I know.

**Comment by marcdumais-work** [comment]
I doubt anyone does, anymore. This was before `open-vsx`, and AFAIK some fixes we did for the `vsix` version, are not present in the npm packages.

**Comment by simevo** [comment]
this documentation here: https://theia-ide.org/docs/composing_applications#consuming-vs-code-extensions should be updated ...

**Comment by vince-fugnitto** [comment]
> this documentation here: https://theia-ide.org/docs/composing_applications#consuming-vs-code-extensions should be updated ...

@simevo updated with what exactly?

**Comment by simevo** [comment]
@vince-fugnitto 
```diff
-    "vscode-builtin-css": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix",
+    "vscode-builtin-css": "https://open-vsx.org/api/vscode/css/1.56.2/file/vscode.css-1.56.2.vsix",
```

etc.

**Comment by vince-fugnitto** [comment]
> 
> ```diff
> -    "vscode-builtin-css": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix",
> +    "vscode-builtin-css": "https://open-vsx.org/api/vscode/css/1.56.2/file/vscode.css-1.56.2.vsix",
> ```

@simevo it's only an example, but if you feel it is worthwhile please open an issue on the [theia-website](https://github.com/eclipse-theia/theia-website/issues). 

We leave the choice up to application developers to where they want to fetch their extensions (by URL). Using `open-vsx`, `github-releases`, or other hosting services are all valid use-cases.

**Comment by marcdumais-work** [comment]
@simevo If you want to be one step ahead, we are perfecting support of `vscode-built-in extensions` through an extension pack: https://github.com/eclipse-theia/theia-blueprint/pull/93

It will make sense to update the examples you point-to, when this is working as we want, since it will permit to replce ~70 built-ins with one pack (maybe a few will need to be pinned to a specific version known to work).

**Comment by marcdumais-work** [comment]
We have deprecated the `npm` version of vscode built-in extensions, that were published early in the life of this repo. We have also updated the example on [theia-website](https://theia-ide.org/docs/composing_applications#consuming-vs-code-extensions) to use the latest and greatest: the vscode built-in extension pack that we now produce. 

For a more practical example you can refer to Theia Blueprint, that also uses the extension pack but pins the few specific extensions that do not work well to versions known to work: [package.json](https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/package.json#L118-L120)

All this should clarify a lot, about which build-ins to use and how.
