### ISSUE TITLE
bug in markdown syntax when line break included in emphasis

### ISSUE THREAD

**Issue by 18kimn** [eclipse-theia/vscode-builtin-extensions#96]
```
*this whole sentence
should have italic formatting in vscode*

_this sentence 
should have it too_

**and this sentence should
be bolded**
```

But currently they show as regular text, and only when the entire string is placed on the same line does the formatting show up.

Here's a [commonmark](https://spec.commonmark.org/dingus/?text=*this%20whole%20sentence%0Ashould%20have%20italic%20formatting%20in%20vscode*%0A%0A_this%20sentence%20%0Ashould%20have%20it%20too_) link showing that this works, and two examples in the spec that have this formatting: [one](https://spec.commonmark.org/0.30/#example-422) [two](https://spec.commonmark.org/0.30/#example-493)

Github supports it too, so you could try it out on a comment.

Not a huge issue of course, since most parsers seem to support this syntax, but just nice to have editor highlighting for it too :)

**Comment by msujew** [comment]
@18kimn I'm not too sure that this issue belongs in this repository. We just consume the [`vscode`](https://github.com/microsoft/vscode) upstream repo to build and upload the extensions they provide. Perhaps you should file your issue there?

**Comment by marcdumais-work** [comment]
Nathan, can you tell us which version of the
scode.markdown-language-features extension you are using? If not sure, you
can look in the "plugins" view.

**Comment by 18kimn** [comment]
Oh, sounds good @msujew, I'll file an issue there! @marcdumais-work I believe I'm using version `1.0.0`

feel free to close this!
