### ISSUE TITLE
Extension 'vscode.git' CANNOT use API proposal: scmValidation.

### ISSUE THREAD

**Issue by Vulxan** [eclipse-theia/vscode-builtin-extensions#97]
Issue Type: <b>Bug</b>

1. Open a Git repo
2. Open OUTPUT

Extension version: 1.62.3
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 6, 6|
|Memory (System)|32.00GB (9.51GB free)|
|Process Argv|people-design --crash-reporter-id 2133163b-be35-40cf-8cb7-cb4a3d4a9511|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3t2:30407763

```

</details>

**Comment by Vulxan** [comment]
![CleanShot 2021-12-23 at 20 45 26@2x](https://user-images.githubusercontent.com/32930147/147242424-827045bb-1e75-4fce-a287-5e104f2e3ce4.png)

**Comment by msujew** [comment]
Hi @Vulxan, I am not too sure this issue belongs here, since it seems to be an actual vscode issue. This is the organization for the [Theia IDE](https://theia-ide.org/), and not vscode. We just consume their builtin vscode extensions. Perhaps you should file your issue there?

**Comment by Vulxan** [comment]
@msujew Thank you for your reply. This issue is automatically submitted here by vscode. I will close this issue first.

**Comment by marcdumais-work** [comment]
Hi Vulxan,

This means that you have installed a built-in extension that we packaged
and published, to be used in Eclipse Theia applications. Our built-in
extensions should not be installed in `vscode` or derivative
products, since they already have a copy. Only trouble may ensue :)

Please uninstall any of our built-ins, and your git should work again.

**Comment by lukas-conlance** [comment]
@marcdumais-work Hi, i ran into the same issue. How can i uninstall a built-in extension? I can't figure it out. 
Thanks in advance 🙂

**Comment by lukas-conlance** [comment]
> @lukas-conlance you installed a builtin provided by this repository in vscode itself?

Yes, VSCodium actually. I can not get rid of it and i'm having the same issue like https://github.com/eclipse-theia/vscode-builtin-extensions/issues/97#issuecomment-1000280479

**Comment by vince-fugnitto** [comment]
@lukas-conlance I'm not sure where exactly vscodium saves it's extensions data, but looking at the [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#migrating-from-visual-studio-code-to-vscodium) it seems to be under `~/.vscode-oss`. You can take a look there to manually remove the duplicate builtin extension (from this repo).

**Comment by lukas-conlance** [comment]
> @lukas-conlance I'm not sure where exactly vscodium saves it's extensions data, but looking at the [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#migrating-from-visual-studio-code-to-vscodium) it seems to be under `~/.vscode-oss`. You can take a look there to manually remove the duplicate builtin extension (from this repo).

Already checked that directory, but i guess it's only for the not built-in extensions :/

**Comment by vince-fugnitto** [comment]
> Already checked that directory, but i guess it's only for the not built-in extensions :/

I guess I'm a little confused :) how were you able to add an external extension as a builtin in vscodium?
Was it not added similarly to an external extension?

**Comment by lukas-conlance** [comment]
I installed the vsix from https://open-vsx.org/extension/vscode/git-base/1.63.0-next.77e1ce431a9 (don't ask why), now it's listed as built-in and it can not be removed.

<img width="1150" alt="Bildschirmfoto 2022-05-05 um 14 59 02" src="https://user-images.githubusercontent.com/68591319/166927873-9b343f93-3ce7-4c5e-98ad-db6e03952f0d.png">
.

**Comment by vince-fugnitto** [comment]
@lukas-conlance unfortunately given that it is pretty specific to vscodium I think asking on their [repo](https://github.com/VSCodium/vscodium) might be more useful (as I'm not sure how vscodium handles this case). In theory given that they already have these builtins as part of their sources they should think of excluding them from being installed by users.

**Comment by vince-fugnitto** [comment]
Also possibly related, there seems to be a bug in https://github.com/VSCodium/vscodium/issues/1038 at the moment.
