### ISSUE TITLE
how to run simplebrowser on runserver

### ISSUE THREAD

**Issue by ashwin31** [eclipse-theia/vscode-builtin-extensions#98]
I am running openvscode server and simplebrowser is not starting automatically when I run project in the web terminal of openvscode.

Is there any configuration to be in place or some automation to be done?

**Comment by vince-fugnitto** [comment]
@ashwin31 thank you for the issue, we do not maintain the `simple-browser` extension (only package and publish it to open-vsx). Does the same use-case occur when you try to use it in vscode itself? Else you might want to open an issue at [openvscode-server](https://github.com/gitpod-io/openvscode-server) itself.

**Comment by ashwin31** [comment]
Thank you @vince-fugnitto I will ask in the openvscode-server repo. I guess, this is not related to vscode itself.
